# This file is auto-generated by nixos-generate-config on the target machine.
# Do NOT edit this file manually.
# It contains disk UUIDs, LUKS devices, and filesystem mounts.
#
# After partitioning and installing on the laptop, copy the generated file here:
#   cp /mnt/etc/nixos/hardware-configuration.nix \
#      ~/.config/nixos/hosts/finns-clanker-station/hardware-configuration.nix
#
# Then run: sudo nixos-rebuild switch --flake ~/.config/nixos#finns-clanker-station
{ config, lib, pkgs, modulesPath, ... }:

{
  imports = [ ];

  # ============================================================================
  # PLACEHOLDER - REPLACE WITH ACTUAL GENERATED CONFIG
  # ============================================================================
  # After running nixos-generate-config on the laptop, this file will contain:
  #
  # boot.initrd.availableKernelModules = [ "xhci_pci" "nvme" "usb_storage" "sd_mod" ];
  # boot.initrd.kernelModules = [ "dm-snapshot" ];
  # boot.kernelModules = [ "kvm-intel" ];
  # boot.extraModulePackages = [ ];
  #
  # fileSystems."/" =
  #   { device = "/dev/disk/by-uuid/XXXX-XXXX";
  #     fsType = "ext4";
  #   };
  #
  # fileSystems."/boot" =
  #   { device = "/dev/disk/by-uuid/YYYY-YYYY";
  #     fsType = "vfat";
  #     options = [ "fmask=0022" "dmask=0022" ];
  #   };
  #
  # swapDevices = [ ];
  #
  # networking.useDHCP = lib.mkDefault true;
  # nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  # hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
  # ============================================================================
}
